name : Node ci
on :
  push :  
    branches : [ main ]
  pull_request :   
    branches : [ main ]
jobs:
  lint:
    runs-on : ubuntu-latest
    steps :
    - name : checkout code
      uses : actions/checkout@v4

    - name : setup Node.js
      uses : actions/setup-node@v4
      with :  
        node-version : 20 
        cache : 'npm'

    - name : install dependencies
      run : npm ci

    - name : Lint code
      run : npm run lint

    tests:
    runs-on : ubuntu-latest
    steps :
    - name : checkout code
      uses : actions/checkout@v4

    - name : setup Node.js
      uses : actions/setup-node@v4
      with :  
        node-version : 20 
        cache : 'npm'

    - name : install dependencies
      run : npm ci
      
    - name : run tests
      run : npm test  
      

      
